# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frames.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66rames.proto\"l\n\x05\x46rame\x12\x0e\n\x06\x63_time\x18\x01 \x01(\x03\x12\x0e\n\x06\x61_time\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x15\n\rbits_per_word\x18\x04 \x01(\x05\x12\x1e\n\nbyte_order\x18\x05 \x01(\x0e\x32\n.ByteOrder*\x1f\n\tByteOrder\x12\x08\n\x04lsbf\x10\x00\x12\x08\n\x04msbf\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frames_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BYTEORDER']._serialized_start=126
  _globals['_BYTEORDER']._serialized_end=157
  _globals['_FRAME']._serialized_start=16
  _globals['_FRAME']._serialized_end=124
# @@protoc_insertion_point(module_scope)
